### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by Joyace** [Baiyuetribe/MyPythonCode#1]
```
root@Joyace:~/OneDriveDownload# python onedrivedl.py https://drive.lolicon97.workers.dev/01%E6%A3%AE%E8%90%9D%E8%B4%A2%E5%9B%A2/ALPHA/ALPHA-005
  File "onedrivedl.py", line 3
SyntaxError: Non-ASCII character '\xef' in file onedrivedl.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by Joyace** [comment]
```
root@Joyace:~/OneDriveDownload# python onedrivedl2.py https://drive.lolicon97.workers.dev/01%E6%A3%AE%E8%90%9D%E8%B4%A2%E5%9B%A2/ALPHA/ALPHA-005/
Traceback (most recent call last):
  File "onedrivedl2.py", line 15, in <module>
    import requests
ImportError: No module named requests
```

**Comment by Joyace** [comment]
```
root@Joyace:~/OneDriveDownload# python onedrivedl.py https://cloud.baiyue.one/?/Books
  File "onedrivedl.py", line 41
    print(f'{title} 已保存成功')
                                   ^
SyntaxError: invalid syntax
```
